### ISSUE TITLE
The result about LoFTR in Table V

### ISSUE THREAD

**Issue by RingoWRW** [LuoXubo/JointLoc#11]
Hi Luo, I believe JointLoc is a remarkable achievement and I am intrigued by this work.  I have a question about Table V. Why can't LoFTR generate matches in textureless regions?

**Comment by LuoXubo** [comment]
Hi, sorry for the confusion. The "failed" here refers to the fact that our device cannot support the matching of LoFTR in large-scale map localization.

**Comment by RingoWRW** [comment]
Thank you for your response. I also have another question regarding Table V. I would like to know the experimental conditions for absolute localization.  I noticed that the error for absolute localization is 10 times larger than SLAM.

**Comment by LuoXubo** [comment]
The experiments are conducted on the RTX 2080Ti. Absolute localization sometimes has very small errors, and sometimes has very large errors. I think the main reason why absolute localization cannot be used alone for UAV is that the positioning result is not smooth enough.
