### ISSUE TITLE
When the main files (vslam in RelLoc and vloc in AbsLoc) will be uploaded?

### ISSUE THREAD

**Issue by hemuyi2024** [LuoXubo/JointLoc#3]
I have found your work to be incredibly insightful and am eager to delve deeper into it. 

Could you kindly let me know **when the main files (vslam in RelLoc and vloc in AbsLoc)** will be uploaded to the repository?

Thank you very much for your time and assistance. I look forward to your response.

**Comment by LuoXubo** [comment]
Hi, thanks for your interest in our work! The main files have been uploaded. You can refer to the RelLoc/vslam.cc and AbsLoc/estimate.py to check the updates.

**Comment by hemuyi2024** [comment]
Thanks, could you write a more detailed explanation for the environment configuration?
 Based on the current instructions, I am not sure how to make the entire system run.

**Comment by LuoXubo** [comment]
Hi, you can refer to `setup.md` to compile the project.

**Comment by hemuyi2024** [comment]
> Hi, you can refer to `setup.md` to compile the project.

Thanks! I have successfully compiled and run the system, but it seems that the SLAM interface is not displaying correctly; the keyframes appear abnormally large, and the scale is incorrect. Could you please advise where this setting can be adjusted?
![Screenshot from 2024-08-23 14-50-20](https://github.com/user-attachments/assets/da02d2cd-367d-48a6-99d9-56da4f0bb9bc)
