### ISSUE TITLE
What is #include "/home/xubo/Codes/slam/jointslam/build/poseInfo.pb.h"

### ISSUE THREAD

**Issue by Oleksandr0605** [LuoXubo/JointLoc#4]
Hello, I am interested in your enhanced version of ORB-SLAM, but something is unclear to me. I do not understand what is the poseinfo.pb.h file and I can't run your slam without it. Thanks.

**Comment by Oleksandr0605** [comment]
Also I have one more question. Do you remove implementation for the fisheye camera?

**Comment by Oleksandr0605** [comment]
Also a big question is one new argument in TrackMonocular. Please, can you explain what it should take?

**Comment by LuoXubo** [comment]
Hi, thanks for your interest in our work! "poseInfo.pb.h" is a customized communication protocol that is produced by Protobuf. It will be generated in /build once you execute the "build.sh" in RelLoc.

**Comment by LuoXubo** [comment]
The new argument in TrackMonocular is the absolute poses estimated by the AbsLoc module. The absolute poses will be sent to the BA module together with the poses generated by the tracker.
