### ISSUE TITLE
[discuss] 关于位置融合的问题

### ISSUE THREAD

**Issue by Wu-ZW** [LuoXubo/JointLoc#5]
感谢作者代码的开源工作。有以下几个疑问未能解决：
1. VO只融合了绝对位置信息（x，y）吗?在浏览代码时，发现其中利用了uav文件夹中的gt.txt真值信息？
2. VO的提供的6自由度信息包含尺度信息吗？还是利用真值进行了尺度的恢复？
![image](https://github.com/user-attachments/assets/35d9e382-13ca-40e3-be88-cb1bfb459010)

**Comment by LuoXubo** [comment]
您好，感谢您的提醒，已修改错误。VO只是融合了绝对位姿，即图中的resX和resY以及置信度conf。其他的参数，如高度z和四元数并未参与位姿融合。
VO提供的6自由度位姿不包含尺度信息，需要通过后端提供的RT矩阵进行对齐。

**Comment by Wu-ZW** [comment]
感谢回复！
1 另外align函数的s，R，t 变换是固定值，是如何计算得到的？
2 AbsLoc中的slam.txt slam_gt.txt gt.txt 分别是起什么作用？ 可以去掉吗？

**Comment by LuoXubo** [comment]
您好，
1. 仿真引擎生成数据的同时，会生成以米为单位的轨迹文件，这里的s,R,t是像素坐标系到仿真引擎坐标系的转换矩阵，通过`evo`工具可以估算得出。
2. 这些是开发过程中用到的中间文件，如果不进行量化评估的话，可以删除。

**Comment by Wu-ZW** [comment]
Thanks a lot~

**Comment by GLFighting** [comment]
> 您好，
> 
> 1. 仿真引擎生成数据的同时，会生成以米为单位的轨迹文件，这里的s,R,t是像素坐标系到仿真引擎坐标系的转换矩阵，通过`evo`工具可以估算得出。
> 2. 这些是开发过程中用到的中间文件，如果不进行量化评估的话，可以删除。

您好，您说的仿真引擎坐标系指的是仿真环境中飞机自身的坐标系吗？
